version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4321}
      - PRODUCTION_FRONTEND=${PRODUCTION_FRONTEND}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=development
      - DEBUG=True
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=noreply@kgr33n.com
      - FROM_NAME=${FROM_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Local PostgreSQL for development/testing
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-portfolio}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
